### ISSUE TITLE
Missing header file zvgFrame.h ?

### ISSUE THREAD

**Issue by gtoal** [palazzol/vmame#1]
zvgintrf.h has this line:

#include "zvgFrame.h"

However the header file does not seem to be present in the repository.

Thanks.

**Comment by fpalazzolo** [comment]
Hi.  That file is part of the ZVG SDK.  It is located inside the zipfile tools/djgpp-gcc343.zip, inside yet another zipfile zvg_sdk11a.zip.  The install.bat process specified in the readme.md should have unzipped and installed it, unless there is a problem.  I don't have a working setup at the moment, but let me know if you still have a problem and I will try to help.

**Comment by palazzol** [comment]
Hi. That file is part of the ZVG SDK. It is located inside the zipfile tools/djgpp-gcc343.zip, inside yet another zipfile zvg_sdk11a.zip. The install.bat process specified in the readme.md should have unzipped and installed it, unless there is a problem. I don't have a working setup at the moment, but let me know if you still have a problem and I will try to help.

**Comment by gtoal** [comment]
Ah - thanks.  I was working from the files visible on the github web pages
because I'm working on creating a vector driver for AdvanceMame for our
PiTrex project (a Pi Zero driving the Vectrex) so I hadn't pulled the
entire ZVG files.  AdvanceMame has the same vector hook as the DOS version
that your ZVG Mame is based on. I had written my own version of the vector
hooks just by inspection from running Battlezone, which sort of worked, but
when I found your code it is much cleaner and better researched so I'm in
the process of rewriting my module based on your zvgintrf.c code, to make a
driver for the PiTrex.  Hence why I hadn't built your version or read the
part of the documentation where that file must have been described.

Graham
